variable "subscription_id" {}
variable "tcp_protocol" {}    
variable "lb_rule_name" {}  
variable "frontend_port" {}   
variable "backend_port" {}   
variable "number_of_nodes" {}
variable "controller_username" {}
variable "controller_password" {}
variable "w_password" {} 
variable "w_username" {}
variable "lb_frontend_ip_conf_name" {}
#variable "ssh_public_key" {}
variable "deny_bgp_route_propagation" {}
